/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'case-studies': CaseStudy;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('es' | 'en') | ('es' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'approach-page': ApproachPage;
    'contact-page': ContactPage;
    'selected-works-page': SelectedWorksPage;
    'extended-works-page': ExtendedWorksPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'approach-page': ApproachPageSelect<false> | ApproachPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'selected-works-page': SelectedWorksPageSelect<false> | SelectedWorksPageSelect<true>;
    'extended-works-page': ExtendedWorksPageSelect<false> | ExtendedWorksPageSelect<true>;
  };
  locale: 'es' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  /**
   * URL: /selected-works/{slug} o /extended-works/{slug}
   */
  slug: string;
  category: 'selected' | 'extended';
  order?: number | null;
  /**
   * Requiere código de acceso (gate)
   */
  private?: boolean | null;
  name: string;
  kicker?: string | null;
  descriptionAccent?: string | null;
  descriptionRest?: string | null;
  stats?: {
    role?: string | null;
    scope?: string | null;
    timeline?: string | null;
    scale?: string | null;
  };
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  cover?: (number | null) | Media;
  /**
   * Secciones del case study (título + cuerpo + media)
   */
  sections?:
    | {
        eyebrow?: string | null;
        title?: string | null;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        media?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  slug?: T;
  category?: T;
  order?: T;
  private?: T;
  name?: T;
  kicker?: T;
  descriptionAccent?: T;
  descriptionRest?: T;
  stats?:
    | T
    | {
        role?: T;
        scope?: T;
        timeline?: T;
        scale?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  cover?: T;
  sections?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
        media?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Colores del sitio (hex, ej. #04816c)
   */
  theme?: {
    accent?: string | null;
    bg?: string | null;
    ink?: string | null;
    muted?: string | null;
    hairline?: string | null;
  };
  brand?: string | null;
  copyright?: string | null;
  menuOpen?: string | null;
  menuClose?: string | null;
  menu?: {
    systems?: string | null;
    approach?: string | null;
    selectedWork?: string | null;
    aboutMe?: string | null;
    extendedWork?: string | null;
    contact?: string | null;
  };
  actions?: {
    startConversation?: string | null;
    connectLinkedIn?: string | null;
    downloadExecutiveCV?: string | null;
    downloadPortfolio?: string | null;
    viewAppliedCases?: string | null;
    enterSystems?: string | null;
    startNow?: string | null;
    back?: string | null;
  };
  statLabels?: {
    role?: string | null;
    scope?: string | null;
    timeline?: string | null;
    scale?: string | null;
  };
  /**
   * Textos del gate de casos privados (LotoBola)
   */
  gate?: {
    eyebrow?: string | null;
    copy?: string | null;
  };
  /**
   * CV en español (PDF)
   */
  cvEs?: (number | null) | Media;
  /**
   * CV in English (PDF)
   */
  cvEn?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  /**
   * Mensajes del hero. Se muestra uno al azar en cada visita.
   */
  messages?:
    | {
        titleAccent?: string | null;
        titleRest?: string | null;
        descriptionAccent?: string | null;
        descriptionRest?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Palabras del loop animado (Estrategia / Sistemas / Ejecución)
   */
  metaItems?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  titleLine1?: string | null;
  titleLine2?: string | null;
  descriptionAccent?: string | null;
  descriptionRest?: string | null;
  meta?: string | null;
  typewriterPrefix?: string | null;
  typewriterAccent?: string | null;
  email?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "approach-page".
 */
export interface ApproachPage {
  id: number;
  titlePrefix?: string | null;
  titleAccent?: string | null;
  systemThinkingTitle?: string | null;
  systemThinkingBody?: string | null;
  integrationTitle?: string | null;
  integrationBody?: string | null;
  executionTitle?: string | null;
  executionBody?: string | null;
  dontTitle?: string | null;
  dontOne?: string | null;
  dontTwo?: string | null;
  dontThree?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  titleLine1?: string | null;
  titleLine2?: string | null;
  descriptionPrefix?: string | null;
  descriptionAccent?: string | null;
  descriptionSuffix?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "selected-works-page".
 */
export interface SelectedWorksPage {
  id: number;
  splashTitleLine1?: string | null;
  splashTitleLine2?: string | null;
  splashDescriptionAccent?: string | null;
  splashDescriptionSuffix?: string | null;
  splashMeta?: string | null;
  segmentLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "extended-works-page".
 */
export interface ExtendedWorksPage {
  id: number;
  titleLine1?: string | null;
  titleLine2?: string | null;
  descriptionAccent?: string | null;
  descriptionRest?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  theme?:
    | T
    | {
        accent?: T;
        bg?: T;
        ink?: T;
        muted?: T;
        hairline?: T;
      };
  brand?: T;
  copyright?: T;
  menuOpen?: T;
  menuClose?: T;
  menu?:
    | T
    | {
        systems?: T;
        approach?: T;
        selectedWork?: T;
        aboutMe?: T;
        extendedWork?: T;
        contact?: T;
      };
  actions?:
    | T
    | {
        startConversation?: T;
        connectLinkedIn?: T;
        downloadExecutiveCV?: T;
        downloadPortfolio?: T;
        viewAppliedCases?: T;
        enterSystems?: T;
        startNow?: T;
        back?: T;
      };
  statLabels?:
    | T
    | {
        role?: T;
        scope?: T;
        timeline?: T;
        scale?: T;
      };
  gate?:
    | T
    | {
        eyebrow?: T;
        copy?: T;
      };
  cvEs?: T;
  cvEn?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  messages?:
    | T
    | {
        titleAccent?: T;
        titleRest?: T;
        descriptionAccent?: T;
        descriptionRest?: T;
        id?: T;
      };
  metaItems?:
    | T
    | {
        text?: T;
        id?: T;
      };
  titleLine1?: T;
  titleLine2?: T;
  descriptionAccent?: T;
  descriptionRest?: T;
  meta?: T;
  typewriterPrefix?: T;
  typewriterAccent?: T;
  email?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "approach-page_select".
 */
export interface ApproachPageSelect<T extends boolean = true> {
  titlePrefix?: T;
  titleAccent?: T;
  systemThinkingTitle?: T;
  systemThinkingBody?: T;
  integrationTitle?: T;
  integrationBody?: T;
  executionTitle?: T;
  executionBody?: T;
  dontTitle?: T;
  dontOne?: T;
  dontTwo?: T;
  dontThree?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  titleLine1?: T;
  titleLine2?: T;
  descriptionPrefix?: T;
  descriptionAccent?: T;
  descriptionSuffix?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "selected-works-page_select".
 */
export interface SelectedWorksPageSelect<T extends boolean = true> {
  splashTitleLine1?: T;
  splashTitleLine2?: T;
  splashDescriptionAccent?: T;
  splashDescriptionSuffix?: T;
  splashMeta?: T;
  segmentLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "extended-works-page_select".
 */
export interface ExtendedWorksPageSelect<T extends boolean = true> {
  titleLine1?: T;
  titleLine2?: T;
  descriptionAccent?: T;
  descriptionRest?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}